# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Message(object):
    def setupUi(self, Message):
        Message.setObjectName("Message")
        Message.resize(552, 461)
        self.centralwidget = QtWidgets.QWidget(Message)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonNO = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNO.setGeometry(QtCore.QRect(406, 390, 60, 60))
        self.pushButtonNO.setAutoFillBackground(False)
        self.pushButtonNO.setText("")
        self.pushButtonNO.setFlat(True)
        self.pushButtonNO.setObjectName("pushButtonNO")
        self.messageBG = QtWidgets.QLabel(self.centralwidget)
        self.messageBG.setGeometry(QtCore.QRect(0, 0, 41, 41))
        self.messageBG.setMaximumSize(QtCore.QSize(552, 461))
        self.messageBG.setObjectName("messageBG")
        self.messageText = QtWidgets.QLabel(self.centralwidget)
        self.messageText.setGeometry(QtCore.QRect(100, 170, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.messageText.setFont(font)
        self.messageText.setScaledContents(True)
        self.messageText.setAlignment(QtCore.Qt.AlignCenter)
        self.messageText.setWordWrap(True)
        self.messageText.setObjectName("messageText")
        self.messageBG.raise_()
        self.pushButtonNO.raise_()
        self.messageText.raise_()
        Message.setCentralWidget(self.centralwidget)

        self.retranslateUi(Message)
        QtCore.QMetaObject.connectSlotsByName(Message)

    def retranslateUi(self, Message):
        _translate = QtCore.QCoreApplication.translate
        Message.setWindowTitle(_translate("Message", "Question"))
        self.pushButtonNO.setToolTip(_translate("Message", "Закрыть"))
        self.messageBG.setText(_translate("Message", "bg"))
        self.messageText.setText(_translate("Message", "messageText"))
