# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question(object):
    def setupUi(self, Question):
        Question.setObjectName("Question")
        Question.resize(552, 461)
        self.centralwidget = QtWidgets.QWidget(Question)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonNO = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNO.setGeometry(QtCore.QRect(406, 390, 60, 60))
        self.pushButtonNO.setAutoFillBackground(False)
        self.pushButtonNO.setText("")
        self.pushButtonNO.setFlat(True)
        self.pushButtonNO.setObjectName("pushButtonNO")
        self.questionBG = QtWidgets.QLabel(self.centralwidget)
        self.questionBG.setGeometry(QtCore.QRect(0, 0, 41, 41))
        self.questionBG.setMaximumSize(QtCore.QSize(552, 461))
        self.questionBG.setObjectName("questionBG")
        self.pushButtonYES = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonYES.setGeometry(QtCore.QRect(320, 390, 60, 60))
        self.pushButtonYES.setAutoFillBackground(False)
        self.pushButtonYES.setText("")
        self.pushButtonYES.setFlat(True)
        self.pushButtonYES.setObjectName("pushButtonYES")
        self.questionText = QtWidgets.QLabel(self.centralwidget)
        self.questionText.setGeometry(QtCore.QRect(40, 200, 461, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.questionText.setFont(font)
        self.questionText.setScaledContents(True)
        self.questionText.setAlignment(QtCore.Qt.AlignCenter)
        self.questionText.setObjectName("questionText")
        self.questionBG.raise_()
        self.pushButtonNO.raise_()
        self.pushButtonYES.raise_()
        self.questionText.raise_()
        Question.setCentralWidget(self.centralwidget)

        self.retranslateUi(Question)
        QtCore.QMetaObject.connectSlotsByName(Question)

    def retranslateUi(self, Question):
        _translate = QtCore.QCoreApplication.translate
        Question.setWindowTitle(_translate("Question", "Question"))
        self.pushButtonNO.setToolTip(_translate("Question", "Закрыть"))
        self.questionBG.setText(_translate("Question", "bg"))
        self.pushButtonYES.setToolTip(_translate("Question", "Нанять"))
        self.questionText.setText(_translate("Question", "questionText"))
