# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_faction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FactionWindow(object):
    def setupUi(self, FactionWindow):
        FactionWindow.setObjectName("FactionWindow")
        FactionWindow.setEnabled(True)
        FactionWindow.resize(1600, 900)
        FactionWindow.setAcceptDrops(False)
        FactionWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(FactionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.faction = QtWidgets.QLabel(self.centralwidget)
        self.faction.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.faction.setMaximumSize(QtCore.QSize(1600, 900))
        self.faction.setAutoFillBackground(True)
        self.faction.setObjectName("faction")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(1000, 830, 40, 40))
        self.pushButtonNext.setAutoFillBackground(False)
        self.pushButtonNext.setText("")
        self.pushButtonNext.setFlat(True)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonPrev = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPrev.setGeometry(QtCore.QRect(550, 830, 41, 40))
        self.pushButtonPrev.setAutoFillBackground(False)
        self.pushButtonPrev.setText("")
        self.pushButtonPrev.setFlat(True)
        self.pushButtonPrev.setObjectName("pushButtonPrev")
        self.pushButtonOK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOK.setGeometry(QtCore.QRect(1137, 830, 41, 40))
        self.pushButtonOK.setAutoFillBackground(False)
        self.pushButtonOK.setText("")
        self.pushButtonOK.setFlat(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(413, 830, 41, 40))
        self.pushButtonBack.setAutoFillBackground(False)
        self.pushButtonBack.setText("")
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName("pushButtonBack")
        FactionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FactionWindow)
        QtCore.QMetaObject.connectSlotsByName(FactionWindow)

    def retranslateUi(self, FactionWindow):
        _translate = QtCore.QCoreApplication.translate
        FactionWindow.setWindowTitle(
            _translate(
                "FactionWindow",
                "Выберите фракцию"))
        self.faction.setText(_translate("FactionWindow", "faction"))
        self.pushButtonNext.setToolTip(
            _translate("FactionWindow", "Следующая раса"))
        self.pushButtonPrev.setToolTip(
            _translate(
                "FactionWindow",
                "Предыдущая раса"))
        self.pushButtonOK.setToolTip(_translate("FactionWindow", "Продолжить"))
        self.pushButtonBack.setToolTip(_translate("FactionWindow", "Назад"))
